1.Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution 
2.Create an array of 20 linearly spaced points between 0 and 1 
3.declare a numpy array of values from 1 to 100 and make it into a 10*10 matrix. 
4.using the previously defined matrix print rows 1,5,6 
5.using the previously defined matrix print elemnts from 3rd row to 10th row 
6.using the previously defined matrix print all elemtnts from 4th column to 8th column 
7.using the same matrix print values from 3rd row 2nd coumn to 5th row 8th column 
8.write a code to generate a 1000 random numbers each in the range(0,1) such that the count of all random points like are almost same . 
9.write the commands to get standard deviation, mean ,mode,median for a given vector

In [1]:
# 1.Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

import numpy as np
rand_num = np.random.normal(0,1,25)
print("25 random numbers sampled from a standard normal distribution:")
print(rand_num)

25 random numbers sampled from a standard normal distribution:
[ 0.64053681 -0.13371689 -1.66522955  0.41835948  1.11042071 -0.17966946
 -0.49498875  1.05976875 -0.33197905  0.7498325   0.64535438  0.03210551
  0.79229102  0.62126224  0.05745694 -0.62011117  0.67530056 -0.16550046
  1.78721529  0.43922403  1.90087255  1.78004497 -0.70496221 -0.88001852
  0.76145833]


In [2]:
#2.Create an array of 20 linearly spaced points between 0 and 1

import numpy as np
lsp = np.linspace(0, 1, 20)
print(lsp)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [8]:
#3.declare a numpy array of values from 1 to 100 and make it into a 10*10 matrix.

import numpy as np
s = np.arange(1,101).reshape(10,10)
print(s)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [11]:
#4.using the previously defined matrix print rows 1,5,6 


print(s[0])
print(s[4])
print(s[5])

[ 1  2  3  4  5  6  7  8  9 10]
[41 42 43 44 45 46 47 48 49 50]
[51 52 53 54 55 56 57 58 59 60]


In [17]:
#5.using the previously defined matrix print elemnts from 3rd row to 10th row 

s[2:11,]

array([[ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [18]:
#6.using the previously defined matrix print all elemtnts from 4th column to 8th column 

s[:,3:8]

array([[ 4,  5,  6,  7,  8],
       [14, 15, 16, 17, 18],
       [24, 25, 26, 27, 28],
       [34, 35, 36, 37, 38],
       [44, 45, 46, 47, 48],
       [54, 55, 56, 57, 58],
       [64, 65, 66, 67, 68],
       [74, 75, 76, 77, 78],
       [84, 85, 86, 87, 88],
       [94, 95, 96, 97, 98]])

In [19]:
#7.using the same matrix print values from 3rd row 2nd coumn to 5th row 8th column 

s[2:5,1:7]

array([[22, 23, 24, 25, 26, 27, 28],
       [32, 33, 34, 35, 36, 37, 38],
       [42, 43, 44, 45, 46, 47, 48]])

In [20]:
#8.write a code to generate a 1000 random numbers each in the range(0,1) such that the count of all random points like are almost same

arr = np.random.randint(0,1,size=1000)
print(arr);

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 

In [22]:
#9.write the commands to get standard deviation, mean ,mode,median for a given vector

import numpy as np
from scipy import stats
values = [99,86,87,88,111,86,103,87,94,78,77,85,86]
Mean = np.mean(values)
print("Mean : ",Mean)
Median = np.median(values)
print("Median : ",Median)
Mode = stats.mode(values)
print("Mode : ",Mode)
sd = np.std(values)
print("Standard Deviation : ",sd)

Mean :  89.76923076923077
Median :  87.0
Mode :  ModeResult(mode=array([86]), count=array([3]))
Standard Deviation :  9.258292301032677
